export const DEFAULT_ALIGN_RADIUS = 100;
export const DEFAULT_COHESION_RADIUS = 50;
export const DEFAULT_SEPARATION_RADIUS = 30;

export const DEFAULT_ALIGN_COEFFICIENT = 1;
export const DEFAULT_COHESION_COEFFICIENT = 1;
export const DEFAULT_SEPARATION_COEFFICIENT = 1.5;

export const DEFAULT_MAX_SPEED = 2;
export const DEFAULT_MAX_FORCE = 0.05;
